### ISSUE TITLE
Code pin desactivé

### ISSUE THREAD

**Issue by nelsou** [lunarok/jeedom_gammu#1]
Hello Lunarok,

J'ai désactivé le code PIN de ma carte SIM. Il faudrait supprimer le début de ce check

`if (config::byKey('pin', 'gammu') == '' || config::byKey('nodeGateway', 'gammu') == '') {
  log::add('gammu', 'error', 'Configuration plugin non remplie, impossible de configurer gammu');
  die();
 } else {`

Merci ! :)

**Comment by lunarok** [comment]
Non, le code pin est utilisé dans le lancement de gammu, c'est pas aussi facile que ca
Il faut le laisser et gammu l'utilise
