### ISSUE TITLE
Wrong user name

### ISSUE THREAD

**Issue by Arno0x** [lunarok/jeedom_gammu#2]
Bonjour,

Voici un problème que j'ai eu, et comment je l'ai réglé, mais je pense que c'est un petit bug d'install.

Après installation du plugin Gammu sur mon Jeedom (_v3.2.7 sur une box Smart_), le démon gammu-smsd ne voulait pas démarrer. Les logs au niveau système (`sudo service gammu-smsd status`) indiquaient une erreur empêchant le démarrage, avec un message `Wrong user name/ID`.

Il se trouve que l'installation par défaut du package gammu-smsd crée le fichier `/etc/init.d/gammu-smsd` et que celui-ci tente d'exécuter le démon avec le user "gammu" (ligne `USER=gammu`) et que cet utilisateur n'existe même pas sur le système, ni n'est créé par l'installation.

Pour faire fonctionner correctement le démon j'ai donc dû changer cette ligne par `USER=root`, utilisateur qui, en plus, a accès au périphérique par `/dev/ttyUSB3`.

Alors il y a sans doute plus propre ou mieux à faire... et surtout gérer cela par le script d'install du plugin gammu parce que en l'état le plugin ne fonctionne pas.

**Comment by lunarok** [comment]
https://github.com/lunarok/jeedom_gammu/commit/af293971b0cfb9661c686c43fc8daea4b23faf1f
suppression du tag smart en tant que plateforme supportée vu que le problème lui est spécifique
